

@app.route('/powers/all')
def powers_all_create():

	names = ['Affliction',
			'Alternate Form',
			'Burrowing',
			'Blast',
			'Communication',
			'Comprehend',
			'Concealment',
			'Create',
			'Damage',
			'Dazzle',
			'Deflect',
			'Elongation',
			'Enhanced Trait',
			'Environment',
			'Heat',
			'Cold',
			'Light',
			'Visibility',
			'Extra Limbs',
			'Insulating Fur',
			'Internal Compartment',
			'Iron Stomach',
			'Mimicry',
			'Quick Change',
			'Specal Effect',
			'Temporal Inertia',
			'Flight',
			'Force Field',
			'Growth',
			'Healing',
			'Illusion',
			'Immortality',
			'Immunity',
			'Insubstantial',
			'Leaping',
			'Luck Control',
			'Mind Reading',
			'Mimic',
			'Mind Control',
			'Mental Blast',
			'Morph',
			'Move Object',
			'Dimension Travel',
			'Environmental Adaptation',
			'Permeate',
			'Safe Fall',
			'Slithering',
			'Space Travel',
			'Sure-Footed',
			'Swinging',
			'Time Travel',
			'Trackless',
			'Wall-Crawling',
			'Water Walking',
			'Nullify',
			'Power Lifting',
			'Protection',
			'Quickness',
			'Regeneration',
			'Remote Sensing',
			'Accurate Sense',
			'Acute Sense',
			'Analytical Sense',
			'Awareness Sense',
			'Communication Link',
			'Counters Concealment Sense',
			'Counters Illusion Sense',
			'Danger Sense',
			'Darkvision',
			'Detect',
			'Direction Sense',
			'Distance Sense',
			'Extended Sense',
			'Infravision',
			'Low-Light Vision',
			'Microscopic Vision',
			'Penetrates Concealment',
			'Postcognition',
			'Precognition',
			'Radio Sense',
			'Sense Radius',
			'Ranged Sense',
			'Rapid Sense',
			'Time Sense',
			'Tracking',
			'Ultra Hearing',
			'Ultravision',
			'Shapeshift',
			'Shrinking',
			'Speed',
			'Suffocation',
			'Snare',
			'Summon',
			'Swimming',
			'Super-speed',
			'Teleport',
			'Transform',
			'Weaken']

	for name in names:

		entry = Power(show=True, name=name, base=True )
		db.session.add(entry)
		db.session.commit()

	results = Power.query.all()

	for r in results:
		print(str(r.id) + ' ' + r.name)

	return ('powers added')